package.json

updating the version of draftjs-to-html version 
ref:- jpuri/draftjs-to-html#28

chore: update draftjs-to-html version

---

stories/ImageSizeValidation/index.story.js

feat(image): add image size validation story

---

stories/PreviewContentOutput/index.story.js

After inserting multiple `<br/>` in Editor it only shows single `<br/>` in preview component
...
...
...
...

fix(preview): fix alignment of break tag in contentOutput

---

src/controls/Link/Component/index.js

fix(link): change CTA and heading

---

css/src/components/dropdown.css
src/decorators/Mention/Suggestion/index.js

fix(mention): scroll by arrow keys

---

src/config/defaultToolbar.js
src/utils/common.js

fix(toolbar): update tooltip name based on platform

---

src/renderer/Image/index.js
src/utils/utils.js

fix(image): image alignment issue in edit and preview state

---

src/Editor/index.js
src/config/defaultToolbar.js
src/renderer/Image/ImageResizer.js
src/renderer/Image/index.js
src/renderer/Image/style.css
src/types/toolbar.js
stories/Editor/index.story.js
stories/Image/index.story.js

feat(image): add option to resize image in editor

---

css/src/components/editor.css
src/Preview/index.js
stories/ConvertStateToHTML/index.story.js
stories/Editor/index.story.js
stories/PreviewContentOutput/index.story.js
stories/PreviewToHTML/index.story.js

Editor Preview support for more than one whitespace in text
...
...
...
...
...

fix(preview): add support to handle whitespaces

---

src/renderer/Image/index.js
src/renderer/Image/style.css

fix(image): add border to avoid flickering issue on resize image

---

src/renderer/Image/ImageResizer.js

fix(image): remove center points to resize image

---

src/Editor/index.js
src/renderer/Image/index.js

fix(image): remove image alignment popover from readonly editor

fix(image): remove image alignment popover from readonly editor

---

src/utils/utils.js

fix(hashtag): prevent hashtag from convert to link in editor

---

src/Editor/index.js

fix(rte): fix copy paste issue in editor

---

stories/AutoExpand/index.story.js

feat(editor): add editor auto expand story

---

src/Editor/index.js
stories/ConvertHTMLToState/index.story.js

fix: update storybook link in prop table and story

---

src/Editor/index.js
src/decorators/Mention/Mention/index.js

feat(mention): pass mention value in custom renderer callback

---

css/src/components/dropdown.css
css/src/components/editor.css
package.json
src/Editor/index.js
src/decorators/Mention/Mention/index.js
src/decorators/Mention/Suggestion/index.js
src/decorators/Mention/addMention.js

Fixes this issue: [Mention Issue](https://github.com/innovaccer/mds-rich-text-editor/issues/87)
...
...
...
...
...

fix(mention): update mention position and overlay

---

.storybook/RichTextEditor.css
src/Editor/index.js
src/decorators/Mention/Suggestion/index.js
stories/MentionCustomPopover/index.story.js

feat(mention): add support for composable mention suggestion popover

---

src/decorators/Mention/Suggestion/index.js

- update selected mention based on passed param values

fix: updating selected mention text based on passed param

---

css/src/components/editor.css
stories/Mention/index.story.js

fix(mention): update mention popover scrollbar
